#version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: handoffmock
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_HOST: "localhost"
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  mynetwork:
    driver: bridge
